# Generated by Django 3.2.11 on 2022-01-23 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('art_type', models.CharField(blank=True, choices=[('painting', 'painting'), ('antique', 'antique'), ('craft', 'craft'), ('furniture', 'furniture')], default='', max_length=15, null=True)),
                ('art_category', models.CharField(choices=[('sketch', 'sketch'), ('canvas painting', 'canvas painting'), ('abstract', 'abstract'), ('coins', 'coins'), ('rare item', 'rare item'), ('paper craft', 'paper craft'), ('wooden craft', 'wooden craft'), ('chair', 'chair'), ('chandelier', 'chandelier'), ('closet', 'closet'), ('table', 'table')], default='Others', max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('original_art_by', models.CharField(max_length=20)),
                ('sold_by', models.CharField(max_length=20)),
                ('canvas_size', models.CharField(choices=[('3x4', '3x4'), ('6x8', '6x8'), ('12x16', '12x16'), ('24x32', '24x32')], default='', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity_available', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to=store.models.get_upload_path)),
                ('width', models.FloatField(default=100)),
                ('length', models.FloatField(default=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product')),
            ],
        ),
    ]
