# Generated by Django 3.2.11 on 2022-01-23 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='canvas_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_sold',
        ),
        migrations.CreateModel(
            name='CanvasSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_size', models.CharField(choices=[('3x4', '3x4'), ('6x8', '6x8'), ('12x16', '12x16'), ('24x32', '24x32')], default='', max_length=50)),
                ('in_stock', models.BooleanField(default=True)),
                ('quantity_available', models.IntegerField()),
                ('quantity_sold', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_product', to='store.product')),
            ],
        ),
    ]
