# Generated by Django 3.2.11 on 2022-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
