# Generated by Django 3.2.11 on 2022-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addr1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='addr2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='alt_contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.TextField(default='standard', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='terms',
            field=models.BooleanField(default=True),
        ),
    ]
