# Generated by Django 3.2.11 on 2022-01-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20220129_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(default='standard', max_length=10),
        ),
    ]
