# Generated by Django 3.2.11 on 2022-01-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20220129_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete')], default='pending', max_length=15),
        ),
    ]
