# Generated by Django 3.2.11 on 2022-01-30 05:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_wishlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlisted',
            field=models.ManyToManyField(blank=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
