# Generated by Django 3.2.11 on 2022-01-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_wishlisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wishlisted',
            new_name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
