# Generated by Django 3.2.11 on 2022-01-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_ratingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ratingreview',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ratingreview',
            name='review',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
