# Generated by Django 3.2.11 on 2022-01-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20220131_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
