# Generated by Django 3.2.11 on 2022-02-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_ratingreview_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_category',
            field=models.CharField(choices=[('sketch', 'sketch'), ('canvas_painting', 'canvas_painting'), ('abstract', 'abstract'), ('coins', 'coins'), ('rare item', 'rare item'), ('paper craft', 'paper craft'), ('wooden craft', 'wooden craft'), ('chair', 'chair'), ('chandelier', 'chandelier'), ('closet', 'closet'), ('table', 'table')], default='Others', max_length=50),
        ),
    ]
