# Generated by Django 3.2.11 on 2022-02-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_product_art_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art_category',
            field=models.CharField(choices=[('sketch', 'sketch'), ('canvas_painting', 'canvas_painting'), ('abstract', 'abstract'), ('coins', 'coins'), ('rare_item', 'rare_item'), ('paper_craft', 'paper_craft'), ('wooden_craft', 'wooden_craft'), ('chair', 'chair'), ('chandelier', 'chandelier'), ('closet', 'closet'), ('table', 'table')], default='Others', max_length=50),
        ),
    ]
