# Generated by Django 3.2.11 on 2022-02-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_art_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
