# Generated by Django 3.2.11 on 2022-02-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_productcategory_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='value',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='producttype',
            name='value',
            field=models.CharField(default='', max_length=15),
        ),
    ]
